# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Joinal Ahmed"
author: "Joinal Ahmed"
email: "joinalahmed@gmail.com"
description: My portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://luxedo.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# ------------------------------------------------------------------------------
# Custom settings
# ------------------------------------------------------------------------------
# Useful links
github_username: "joinalahmed"
facebook_username: "joinalahmed"
twitter_username: "joinal_ahmed"
linkedin_id: "joinalahmed"

# Theme
# theme: jekyll-theme-potato-hacker                 # Uncomment this
remote_theme: luxedo/jekyll-theme-potato-hacker   # Or this
theme_repository: "https://github.com/luxedo/jekyll-theme-potato-hacker"
theme_base: "light"       # Theme palette (light | dark)
theme_switch: on         # Show color switch (on | off)

# Extra settings
blog: on                 # Show blog tag and post list (on | off)
avatar: on               # Show avatar (on | off)
avatar_image: "assets/img/joy.jpg"
avatar_description: "My name is Luiz Joinal and I like making and breaking stuff."
highlighter_theme: monokai  # Theme of the syntax_highlighter [base16 |
                            # colorful | github | gruvbox | molokai |
                            # monokai | pastie | thankful_eyes | tulip ]
toolbar_priority:        # Order of the items in the toolbar (except for blog and home)
  - Web
  - Open Source
  - Games
  - Other

# Collections
collections:
  dropdown:
    output: true
  items:
    output: true
# ------------------------------------------------------------------------------

# Build settings
excerpt_separator: "<!--more-->"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
